name: ubuntu_flavor_installer
description: Ubuntu Flavor Installer
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_html: 3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  handy_window: ^0.3.0
  ubuntu_bootstrap:
    path: vendor/ubuntu-desktop-provision/packages/ubuntu_bootstrap
  ubuntu_flavor: ^0.2.0
  ubuntu_utils:
    path: vendor/ubuntu-desktop-provision/packages/ubuntu_utils
  url_launcher: ^6.1.8
  yaru: ^0.9.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  melos: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/slides/
    - assets/theme/
